baseURL = "https://anxoportela.github.io/"
title = "Portfolio"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
enableGitInfo = true
#disqusShortname = "https-anxoportela-github-io"

[params]
author = "Anxo Portela-Insua Blanco"
description = "Anxo Portela's personal website"
keywords = "blog,developer,personal,qa,automation,selenium,postman,jmeter,soapui,cucumber"
info = ["QA Automation Engineer"]
avatarURL = "images/avatar.jpg"
dateFormat = "2006-01-02"
since = 2022
commit = "https://github.com/anxoportela/blog.site/commit/"
rtl = false
colorScheme = "dark"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
enableTwemoji = true
customCSS = ["css/custom_style.css", "css/form.css"]
customSCSS = []
customJS = []

[params.googleTagManager]
id = "G-FRXS7FM4QF"

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", 
    "https://fonts.gstatic.com", 
    "https://cdn.jsdelivr.net/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
formaction = [
    "'self'",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
framesrc = [
    "'self'",
    "https://disqus.com/",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
imgsrc = [
    "'self'",
    "https://referrer.disqus.com/",
    "https://c.disquscdn.com/",
    "https://cdn.viglink.com/",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
objectsrc = ["'none'"]
stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com/",
    "https://cdn.jsdelivr.net/",
    "https://c.disquscdn.com/",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://www.google-analytics.com",
    "https://cdn.jsdelivr.net/",
    "https://https-anxoportela-github-io.disqus.com/",
    "https://disqus.com/",
    "https://c.disquscdn.com/",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
prefetchsrc = [
    "'self'",
    "https://https-anxoportela-github-io.disqus.com/",
    "https://disqus.com/",
    "https://c.disquscdn.com/",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]
connectsrc = [
    "'self'",
    "https://www.google-analytics.com", 
    "https://links.services.disqus.com/",
    "https://docs.google.com/",
    "https://www.googletagmanager.com/",
    "*.google-analytics.com"
]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/anxoportela"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/anxoportela"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://anxoportela.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"

[languages.es]
languageName = ":es:"
title = "Portfolio"

[languages.es.params]
author = "Anxo Portela-Insua Blanco"
info = "Ingeniero QA Automatización"
description = "Sitio personal de Anxo Portela"
keywords = "blog,desarrollador,personal,qa,automatización,selenium,postman,jmeter,soapui,cucumber"

[[languages.es.menu.main]]
name = "Acerca de"
weight = 3
url = "about/"

[[languages.es.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.es.menu.main]]
name = "Proyectos"
weight = 2
url = "projects/"

[[languages.es.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"
